### ISSUE TITLE
Drop engines specification from package.json

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-plugin-whitelist#31]
I think engines spec is no longer needed in package.json since cordova-android@4.0.0 is already pretty old and no longer supported. Dropping the engines spec should get rid of the sporadic "version check failed ... continuing anyways" messages reported in <https://github.com/apache/cordova/issues/52>.

I wonder if we should also consider a major version bump of this plugin.

**Comment by janpio** [comment]
That specification is here all the time, why should it trigger a "sporadic" failing check?

**Comment by brodybits** [comment]
It looks like something going wrong with superspawn in apache/cordova#52, unfortunately cannot explain it any better.

**Comment by jcesarmobile** [comment]
I don't think removing the engines in this plugin will solve anything, because we have engines in all plugins, so if it fails here it should also fail in any other plugin.

**Comment by jcesarmobile** [comment]
the plugin is being deprecated and we need the engines to prevent users from installing in cordova-android 10, so going to close the issue
