### ISSUE TITLE
Not working with cordova-plugin-hello-c

### ISSUE THREAD

**Issue by LucaTrip** [apache/cordova-plugin-whitelist#36]
I'm trying to integrate the `cordova-plugin-hello-c` plugin to my project, but I realized that it conflicts whit this plugin. In the sense that if I only install `cordova-plugin-hello-c`, this works. if only `cordova-plugin-whitelist` is installed, it works correctly making me HTTP requests. Depending on the order in which the two plugins are installed, either one does not work or the other does not work. If `cordova-plugin-hello-c` does not work, it returns **class not found**, but if I do not work `cordova-plugin-whitelist`, I will fail HTTP requests and return 404.
My project info

> Ionic:
>    ionic (Ionic CLI)  : 4.2.1
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.1
> 
> Cordova:
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.4
>    Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 1 other plugins)
> 
> System:
>    Android SDK Tools : 26.1.1
>    NodeJS            : v9.2.0 
>    npm               : 5.5.1
>    OS                : Linux 4.15
>

**Comment by janpio** [comment]
Seems like a problem with the other plugin, not this one.

**Comment by jcesarmobile** [comment]
Try updating to cordova-android 7.1.4, previous versions had problems with `cordova-plugin-hello-c`

**Comment by LucaTrip** [comment]
I upgraded cordova-android to version 7.1.4, but the problem still persists.

**Comment by dpa99c** [comment]
This is the same issue as I opened here: https://github.com/apache/cordova-android/issues/683

I'm not convinced it's specific to `cordova-plugin-whitelist` or [cordova-plugin-hello-c](https://github.com/dpa99c/cordova-plugin-hello-c) since neither does anything particularly funky with their `plugin.xml` or hook scripts, etc.

When I get a mo I'll try to repro with other plugins to confirm the above assumption.

**Comment by luisdemarchi** [comment]
This looks like a bug in the cordova-android repository, I've tried to contribute something like I solved on https://github.com/apache/cordova-android/issues/683

**Comment by jcesarmobile** [comment]
closing in favor of the linked cordova-android issue
