### ISSUE TITLE
android Not allowed to load local resource

### ISSUE THREAD

**Issue by happyi** [apache/cordova-plugin-whitelist#37]
config.xml
```
<content src="http://ylh-test.mezeron.cn/yiren-remote/index.html" />
    <access origin="cdvfile://*" />
    <access origin="content:///*" />
    <access origin="file://*" />
    <access origin="*" />
    <allow-navigation href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-intent href="cdvfile://*" />
```
load img like below 
```
<img src="file:///storage/emulated/0/Android/data/cn.mezeron.yiren.test/cache/1554273302432.jpg"/>
```
it's get error:

 Not allowed to load local resource: file:///storage/emulated/0/Android/data/cn.mezeron.yiren.test/cache/1554273302432.jpg

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
