### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-whitelist#39]
# Feature Request

## Motivation Behind Feature

The tests added via #38 only cover a small part of the actual plugin functionality. This should be improved or increased confidence.

## Feature Description

- Test `allow-intent`
- Test `access`
- Add iOS tests: iOS also has a whitelist, although not via this plugin the tests could/should apply equally: https://cordova.apache.org/docs/en/9.x/guide/appdev/whitelist/index.html#ios-whitelisting

## Alternatives or Workarounds
none

**Comment by janpio** [comment]
iOS tests were part of the test plugin before, but removed with https://github.com/apache/cordova-mobile-spec/pull/133 - maybe it is enough to recreate that code.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
