### ISSUE TITLE
Update to 1.3.4 -> error

### ISSUE THREAD

**Issue by tux240** [apache/cordova-plugin-whitelist#44]
Hello,

I would like to update this plugin to the 1.3.4 version but I have an error notarget.

> npm ERR! notarget No matching version found for cordova-plugin-whitelist@^1.3.4

How can I update it ?
Thanks

**Comment by erisu** [comment]
Version `1.3.4` has not been released and is in a vote for approval. Once the vote has passed, it would then be made public. Please monitor npmjs for the release of the new version.

https://www.npmjs.com/package/cordova-plugin-whitelist
