### ISSUE TITLE
Blacklist origin: give access to all origins except a blacklist

### ISSUE THREAD

**Issue by Aljabri-Salman** [apache/cordova-plugin-whitelist#46]
Is it possible to give access to all origins except some. How to achieve that?

**Comment by Rlamotte** [comment]
I have the same problem : i have a cordova WebView app (using Phonegap InAppBrowser) which is used to connect to different WebSite depending on users parameters. 

In those webSite, allow-notification should be always active to view pages in the InAppBrowser, and not on default android browser. But on those webSite, i must prevent user for going out of app (with embedded Youtube Iframe redirection, link to social media,...).

Today i'm forced to put all webSite in allow-navigation but it's hard to maintain when new webSite must be added.

It would be awesome to jsut put "<disallow-navigation="https://youtube.com/*>".

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
