### ISSUE TITLE
Port Whitelist naming & terms to Allowlist (or alternative)

### ISSUE THREAD

**Issue by King-of-Spades** [apache/cordova-plugin-whitelist#57]
# Feature Request
This is a request to port the `Whitelist` terminology in the name of this repository, code, and documentation, to `Allowlist` or another appropriate equivalent. 

## Motivation Behind Feature
1. `Whitelist` though a familiar industry term, is insensitive due to bias, e.g. `white == good`. 
2. It's a poor descriptor since `white` is more abstract than `allow`.
3. `Allow` is consistent with the operational syntax:
`<allow-navigation href="http://example.com/*" />`

## Feature Description
At a glance, it appears to me like most of the changes would be needed in documentation and package naming, though I haven't confirmed this. 

A potential challenge is the name of the package and repository itself since that could be a breaking change downstream.

**Comment by breautek** [comment]
> A potential challenge is the name of the package and repository itself since that could be a breaking change downstream.

`whitelist` plugin on NPM would just simply be deprecated and no longer pushed to. The repo itself I believe can be renamed and the old repo url I believe will be redirected... one would have to confirm though.

We do have a meta ticket for this located at https://github.com/apache/cordova/issues/218 but that is abstract. It's good to have a ticket for this repo specifically.

**Comment by King-of-Spades** [comment]
> The repo itself I believe can be renamed and the old repo url I believe will be redirected... one would have to confirm though.

That's standard with GitHub repo renaming, and even mentioned on the settings for it. I've never had an issue with my own renamed repos. However, the GitHub settings do warn that it could break things, I'm not sure what integration scenarios would be potentially risky or not.

**Comment by breautek** [comment]
> However, the GitHub settings do warn that it could break things, I'm not sure what integration scenarios would be potentially risky or not.

I'd have to test but I seem to recall the website will redirect but stuff like ssh urls will return with a repo does not exist kind of error.

**Comment by timbru31** [comment]
AFAIK repos are redirected, username changes are not.

**Comment by jcesarmobile** [comment]
The plugin is being deprecated and integrated into cordova-android with a new AllowList name https://github.com/apache/cordova-android/pull/1138

So we won't be doing any renaming in this repository
