### ISSUE TITLE
cordova-plugin-whitelist does not support cordova-android 10.x

### ISSUE THREAD

**Issue by danny-lai-queo** [apache/cordova-plugin-whitelist#64]
# Feature Request

## Motivation Behind Feature
Now that cordova-android  10.0.0  is out .   This plugin should support cordova-android 10+

## Feature Description
Please update this plugin to support cordova-android 10+

## Alternatives or Workarounds
no workaround

**Comment by danny-lai-queo** [comment]
the readme  mentioned  cordova android 10 does not need this plugin .

**Comment by breautek** [comment]
The plugin is deprecated. See https://github.com/apache/cordova-plugin-whitelist#deprecation-notice

Cordova-android has the same implementation (renamed to allow list) built in now.
