### ISSUE TITLE
After updating plugin 1.3.5 error in http request

### ISSUE THREAD

**Issue by luisd-morales** [apache/cordova-plugin-whitelist#65]
# Bug Report
After updating plugin 1.3.5 error in http request
## Problem

when I update the plugin 1.3.5 and cordova to 10.0.1 my application that worked correctly... stopped working

### What is expected to happen?

the plugin works normally with http settings or mixed content

### What does actually happen?

after updating the application same error  Mixed Content: The page at 'https://localhost/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest

### Command or Code

My config.xml

```
<allow-navigation href="*" />
        <allow-intent href="http://*/*" />
        <allow-intent href="https://*/*" />
        <allow-intent href="tel:*" />
        <allow-intent href="sms:*" />
        <allow-intent href="mailto:*" />
        <allow-intent href="geo:*" />

```

### Environment, Platform, Device

Android and IOS

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
